import type { Item } from "@/types";

export const items: Omit<Item, 'quantity'>[] = [
  {
    id: 'REGSHA',
    order: 1,
    name: "Chicken Regular Shawarma (with salad)",
    type: "Non-Veg",
    category: "Shawarma",
    price: 110,
  },
  {
    id: 'SPLSHA',
    order: 2,
    name: "Chicken Special Shawarma (without salad)",
    type: "Non-Veg",
    category: "Shawarma",
    price: 130,
  },
  {
    id: "CHPSHA",
    order: 3,
    name: "Chicken Chips Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 140,
  },
  {
    id: 'PPSHA',
    order: 4,
    name: "Chicken Peri-Peri Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 140,
  },
  {
    id: 'SCHSHA',
    order: 5,
    name: "Chicken Schezwan Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 150,
  },
  {
    id: "CHSSHA",
    order: 6,
    name: "Chicken Cheese Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 150,
  },
  {
    id: "TRKSHA",
    order: 7,
    name: "Chicken Turkish Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 150,
  },
  
  {
    id: "LAVSHA",
    order: 8,
    name: "Lavish Special Shawarma",
    type: "Non-Veg",
    category: "Shawarma",
    price: 200,
  },
  {
    id: "FALSHA",
    order: 9,
    name: "Special Veg Falafel Shawarma",
    type: "Veg",
    category: "Shawarma",
    price: 110,
  },
  {
    id: "LOADBOWL",
    order: 10,
    name: "Chicken Loaded Bowl",
    type: "Non-Veg",
    category: "Bowls",
    price: 200,
  },
  {
    id: "FFRIES",
    order: 11,
    name: "French Fries",
    type: "Veg",
    category: "Fries",
    price: 90
  },
   {
    id: "FFPPRIES",
    order: 12,
    name: "French Fries with Peri-Peri",
    type: "Veg",
    category: "Fries",
    price: 90
  },
  {
    id: "WB",
    order: 13,
    name: "Water bottle",
    type: "Veg",
    category: "Drinks",
    price: 10,
  },
  {
    id: "EXTMAYO",
    order: 14,
    name: "Extra Mayonnaise",
    type: "Non-Veg",
    category: "Add-ons",
    price: 10
  },
  {
    id: "THUMBSUPSM",
    order: 15,
    name: "Thumbs Up Small",
    type: "Veg",
    category: "Drinks",
    price: 10,
  },
  {
    id: "SPRITESM",
    order: 16,
    name: "Sprite Small",
    type: "Veg",
    category: "Drinks",
    price: 10,
  },
  {
    id: "THUMBSUP",
    order: 17,
    name: "Thumbs Up medium",
    type: "Veg",
    category: "Drinks",
    price: 15,
  },
  {
    id: "SPRITE",
    order: 18,
    name: "Sprite medium",
    type: "Veg",
    category: "Drinks",
    price: 15,
  },
  {
    id: "THUMBSUP",
    order: 19,
    name: "Thumbs Up Large",
    type: "Veg",
    category: "Drinks",
    price: 20,
  },
  {
    id: "SPRITE",
    order: 20,
    name: "Sprite Large",
    type: "Veg",
    category: "Drinks",
    price: 20,
  }
];
